{% set name = "dynophores" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wolberlab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: d3bbbdfce1550af8663fd9d85d33ad139ad59257e80017a55da8728a2636a8c6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - dynoviz = dynophores.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.12
    - numpy
    - pandas
    - matplotlib-base
    - seaborn
    - jupyter
    - jupyterlab
    - ipywidgets
    - ipympl
    - nglview
    - rdkit
    - mdanalysis

test:
  imports:
    - dynophores
  commands:
    - dynoviz -h

about:
  home: https://github.com/wolberlab/dynophores
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dynamic pharmacophore modeling of molecular interactions'
  description: |
    Dynamic pharmacophore modeling of molecular interactions.
    Dynophores are an intuitive tool to explore the dynamics 
    of molecular interactions between a macromolecule and a ligand 
    throughout an MD simulation.
  doc_url: https://dynophores.readthedocs.io/en/latest/
  dev_url: https://github.com/wolberlab/dynophores

extra:
  recipe-maintainers:
    - dominiquesydow
