{% set name = "dynophores" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dominiquesydow/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 4eeb0233818b65f9e9d99b8b8fe8ab86ed5c12ac818556cdb1ce72d05686443c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - dynoviz = dynophores.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas  
    - matplotlib-base
    - seaborn
    - jupyter
    - jupyterlab
    - ipywidgets
    - ipympl
    - nglview
    - rdkit
    - mdanalysis

test:
  imports:
    - dynophores
  commands:
    - dynoviz -h

about:
  home: https://github.com/dominiquesydow/dynophores
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dynamic pharmacophore modeling of molecular interactions'
  description: |
    Dynamic pharmacophore modeling of molecular interactions.
    Dynophores are an intuitive tool to explore the dynamics 
    of molecular interactions between a macromolecule and a ligand 
    throughout an MD simulation.
  doc_url: https://dynophores.readthedocs.io/en/latest/
  dev_url: https://github.com/dominiquesydow/dynophores

extra:
  recipe-maintainers:
    - dominiquesydow
