{% set name = "dynophores" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dominiquesydow/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 0a8d72793d1d35d586e386c3eb57f72b5ba4d80600b0f71fcd34b764e13ee0fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dynoviz = dynophores.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - matplotlib-base
    - seaborn
    - jupyter
    - jupyterlab
    - ipywidgets
    - ipympl
    - nglview
    - rdkit
    - mdanalysis

test:
  imports:
    - dynophores
  commands:
    - dynoviz -h

about:
  home: https://github.com/wolberlab/dynophores
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dynamic pharmacophore modeling of molecular interactions
  description: |
    Dynamic pharmacophore modeling of molecular interactions.
    Dynophores are an intuitive tool to explore the dynamics 
    of molecular interactions between a macromolecule and a ligand 
    throughout an MD simulation.
  doc_url: https://dynophores.readthedocs.io/en/latest/
  dev_url: https://github.com/wolberlab/dynophores

extra:
  recipe-maintainers:
    - dominiquesydow
